# Generated by Django 3.0.4 on 2020-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='assigned_type',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient Ambulance', 'Outpatient Ambulance'), ('Outpatient Office', 'Outpatient Office')], default='Inpatient', max_length=30),
        ),
        migrations.AddField(
            model_name='encounter',
            name='requested_type',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('Outpatient Ambulance', 'Outpatient Ambulance'), ('Outpatient Office', 'Outpatient Office')], default='Inpatient', max_length=30),
        ),
        migrations.AddField(
            model_name='encounter',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='facility',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facility',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='taxid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='facility',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Decline to answer', 'Decline')], default='Other', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='physician',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='physician',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='physician',
            name='fax',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='physician',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='physician',
            name='taxid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='physician',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='charting',
            field=models.TextField(blank=True),
        ),
    ]
